theme: minima
title: Blog de Alex
author: Alejandro Gallegos
email: galejandro@vivaldi.net
description: > # this means to ignore newlines until "baseurl:"
  Blog centrado en el aprendizaje de análisis de datos con _R_ y _Python_

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
